### ISSUE TITLE
TZ coding

### ISSUE THREAD

**Issue by misscheevius** [burnedikt/diasend-nightscout-bridge#37]
Hello,
I’m really grateful and excited for this.
I’m having trouble with time zones. I note your configuration instructions.
Can you please advise what TZ variable should look like? I’m in Adelaide, ACDT, GMT+10:30. I’ve tried ACDT, 10:30 and +10:30 and it doesn’t seem to be right. Would appreciate an exemplar of how this should be entered for it to work. 
I have merged successfully and data is coming through, but just a few things to sort for it to work properly for me. 
Thanks very much in anticipation.

**Comment by burnedikt** [comment]
Hey @misscheevius, glad you like it.

You should be able to set the `TZ` variable to `Australia/Adelaide` and be all set. It doesn't work without the `Australia/...` prefix.

**Comment by burnedikt** [comment]
@misscheevius was your issue resolved?
