### ISSUE TITLE
plain http access to ns api?

### ISSUE THREAD

**Issue by conan222** [burnedikt/diasend-nightscout-bridge#42]
Great work, but I am in dispair… Ist there any chance to contact the nightscout api via http? I do not get the plugin version running, so I try to run it side-by-side to Nightscout via docker compose on my nas behind a reverse proxy so nightscout provides it‘s api via http. The diasend client has no problem contacting diasend and get the data but is not able to send it to nightscout claimin „AxiosError: … ssl3_get_record: wrong version“, „code: EPROTO, errno: -71“? Thanks for any help!

**Comment by burnedikt** [comment]
Seems like the bridge is trying to talk to NS via https when it should use http... how did you configure `NIGHTSCOUT_URL`? Should be something like `http://<name-of-nightscout's-docker-compose-service-or-container-name>` in your setup.

**Comment by conan222** [comment]
I am sorry - you are right…. For some reason my nas seem to redirect the request to https. It is nothing related to your solution. Thanks for your quick reply!
