### ISSUE TITLE
TZ: value?

### ISSUE THREAD

**Issue by atomphil** [burnedikt/diasend-nightscout-bridge#43]
I have the problem that the data from Diasend in Nightscout are shifted by one hour, the CGM values which are sent directly from xDrip (Companion to CamAPS) to Nightscout are correct. 

Nightscout runs as a webapp (forked from [https://github.com/burnedikt/cgm-remote-monitor](https://github.com/burnedikt/cgm-remote-monitor)) at Northflank with an Atlas Mongo DB. My time zone is Germany (UTC+1 or GMT+1).

I think setting the TZ variable would fix the problem, but unfortunately it doesn't say in the examples what value I have to assign to it.

How does the whole construction actually behave during the daylight saving time changeover?

**Comment by burnedikt** [comment]
Just set `TZ` to '`Europe/Berlin`. List of timezone values accepted by nodejs: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.

Unless you specify the `TZ` as only the offset to UTC (e.g. `UTC-01:00`, the information about daylight saving time (DST) is implicitly known. I.e. don't use `GMT+01:00` but use `Europe/Berlin` instead.

**Comment by burnedikt** [comment]
Simple browser-based utility to find out your current timezone: 

https://js-qxakt9.stackblitz.io

(Will not work if you altered your device's timezone manually).
