### ISSUE TITLE
help for nightscout plugin

### ISSUE THREAD

**Issue by Heiner1** [burnedikt/diasend-nightscout-bridge#46]
Hi Benedikt
I'm in the Looper Community since 2016 and happy to use the mylife CamAPS FX now. It's so simple and for many T1Ds a great advantage. But the collaboration of the different sharing companies is not the best. The idea to get readings and treatments into the web-monitor is, my opinion, the best. 
I appreciate your generous work. 
Weeks ago I tried to get it on the run, but seems to heavy for me. So I wanted to ask you how to integrate your npm in cgm-remote-monitor? I tried to merge it, but that seems to be be the wrong way. 
If you know some examples how to do, I'll try it again. 
Thanks in advance

**Comment by burnedikt** [comment]
Hey, there's a couple of ways to make this work with nightscout / cgm-remote-monitor. I am assuming you have a running nightscout instance already and are just looking to get the diasend-nightscout-bridge integrated. 

1. My cgm-remote-monitor fork here on github has the diasend-nightscout-bridge readily integreated. Therefore, you can either fork my repository directly and deploy it as your nightscout instance or merge the changes from my updated fork of cgm-remote-monitor into your fork of cgm-remote-monitor. The latter makes sense if you've already performed some modifications of your cgm-remote-monitor. You can easily do this, by using the following link which shows the changes / differences between your nightscout / cgm-remote-monitor fork and mine: https://github.com/Heiner1/cgm-remote-monitor/compare/master...burnedikt:cgm-remote-monitor:master. You can then use the "Create Pull Request" button and merge it. This will run the bridge as a plugin directly within nightscout as mentioned in the [readme](https://github.com/burnedikt/diasend-nightscout-bridge#nightscout-plugin)
2. If you're not afraid to run additional servers next to your nightscout instance, you can follow the instructions for deploying the bridge [standalone / as a sidecar](https://github.com/burnedikt/diasend-nightscout-bridge#standalone--sidecar)
3. You can wait until the bridge becomes a plugin which is integrated out-of-the-box with nightscout. There are multiple PRs to make this happen (https://github.com/nightscout/cgm-remote-monitor/pull/7820 and https://github.com/nightscout/cgm-remote-monitor/pull/7872) but it's worth nothing those PRs have been stalled for some time and it's unclear when the changes will make it upstream. Once this happens, though, no additional effort would be required apart from configuring the `ENABLE` variable and `DIASEND_*` credentials as mentioned in the [docs](https://github.com/nightscout/cgm-remote-monitor/pull/7872)

I would recommend to go with Option 1 for now. Let me know if that helps!

**Comment by MiGerth** [comment]
By the way the first nightscout serive provider has integreted the bridge: https://ns.10be.de There you only have to enter your diasend credentials :-)
